### ISSUE TITLE
panic: abi: cannot use string as type array as argument

### ISSUE THREAD

**Issue by yisar** [chenzhijie/go-web3#20]
allowance, err := contract.Call("allowance", web3.Eth.Address(), "0x0000000000000000000000000000000000000002")
	if err != nil {
		panic(err)
	}

**Comment by Dou-xx** [comment]
> ```
> allowance, err := contract.Call("allowance", web3.Eth.Address(), "0x0000000000000000000000000000000000000002")
> if err != nil {
> 	panic(err)
> }
> ```

common.HexToAddress("0x0000000000000000000000000000000000000002")
