### ISSUE TITLE
init web3 panic

### ISSUE THREAD

**Issue by shaokun11** [chenzhijie/go-web3#3]
go1.17.5 windows when init like ` web31, err := web3.NewWeb3(infuraURL)`,the error is 
dial unix https://mainnet.infura.io/v3/xxx: connect: An invalid argument was supplied

**Comment by shaokun11** [comment]
![image](https://user-images.githubusercontent.com/40231565/146746894-626e52cf-93d1-441c-b9f2-ca4d6787e764.png)

I found the error position is here

**Comment by chenzhijie** [comment]
You should provide a right provider url here. You can go to https://infura.io and register your api key, then replace your api key in the code.

**Comment by shaokun11** [comment]
now it work, thanks your efffort
