### ISSUE TITLE
Nil value is returning after calling any write contract method.

### ISSUE THREAD

**Issue by MadhuS-1605** [chenzhijie/go-web3#8]
Read contract methods can be called without any issue but, when we call a write contract method with proper args value it is returning nil data.

**Comment by iSumitBanik** [comment]
Hey, Can you guide me the syntax to use the `contract.Call()` method for a write contract method?
I am not getting it anywhere.

Thanks :)

**Comment by MadhuS-1605** [comment]
> Hey, Can you guide me the syntax to use the `contract.Call()` method for a write contract method? I am not getting it anywhere.
> 
> Thanks :)

sure i can.
Drop me a mail to (madhusgowda56@gmail.com) your discord ID i'll help you with your problem
