### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by huangqian1985** [chenzhijie/go-web3#9]
在找类似web3.js的golang实现的时候看到了你这个库，我最近也在学习这方面的内容, 不知道方不方便加个QQ或者微信交流

**Comment by MadhuS-1605** [comment]
> 在找类似web3.js的golang实现的时候看到了你这个库，我最近也在学习这方面的内容, 不知道方不方便加个QQ或者微信交流

what kind of help do you need?

**Comment by chenzhijie** [comment]
有需要交流的，可以直接提issue或者pr
